### PR TITLE
Add missing lutris.util.egs for installation

### PR DESCRIPTION
**Pull request by rezzafr33**

### CODE REVIEW

**Comment by buxel** [comment]
@rezzafr33 Sorry for the delay but i somehow missded the notification for your PR. Could you please rebase it so i can accept the PR?

**Comment by buxel** [comment]
I'm sorry, something seems to be off. It says you want to merge 60 commits and 50 file changes. 
Could you open a fresh, clean PR? 
Alternatively - if you don't mind - i could add your changes manually. It's easier but you won't get credits for them.

**Comment by rezzafr33** [comment]
i don't mind, feel free to add it manually.

**Comment by buxel** [comment]
Thank you. I added your changes in 1280eaf1ae1a6a9d0a7d0ebd13caee418b82c73c

**Pull request closed without merging**
